### ISSUE TITLE
SImple issue that needs to fix

### ISSUE THREAD

**Issue by STEdirisuriya** [fossasia/labyrinth#206]
### Expected results
Great UI

### Actual results
There are lot of small and big issues.

### Steps to reproduce the issue
- [ ] Use characters that haven't white space.
![this](https://user-images.githubusercontent.com/33794760/34642457-6b3bf804-f339-11e7-8605-4c30f6ae2b16.png)

- [ ] Add single colour to background of game 
![image](https://user-images.githubusercontent.com/33794760/34642469-92c8aa02-f339-11e7-83c5-f758d5f4a991.png)

- Remove this word on tile or change word effect for looks it good.
![image](https://user-images.githubusercontent.com/33794760/34642476-c9d9e8f8-f339-11e7-9bb5-5d5f6728be74.png)

- [ ] Add a option to change character on menubar.
![image](https://user-images.githubusercontent.com/33794760/34642502-014169a6-f33a-11e7-9c42-05f7354bfd6e.png)

- [ ] Center align all icons of social.
![image](https://user-images.githubusercontent.com/33794760/34642511-28b185fc-f33a-11e7-9a84-f377b2687f61.png)

- [ ] Add an about window and add social icons, UI creator, Contributors, brief description on it.
![image](https://user-images.githubusercontent.com/33794760/34642567-e23ca1be-f33a-11e7-991b-abb587c0f805.png)

- [ ] Close rooms like rooms that has a key after one time enter to avoid give key twice or make a method for not give key twice from same place.
![image](https://user-images.githubusercontent.com/33794760/34642582-52b158fe-f33b-11e7-9e9f-6f715ca0319a.png)

- [ ] Add a music to tiles when we enter to them and add music too that plays on background.

- [ ] This tile came out from walls, please resolve it.
![image](https://user-images.githubusercontent.com/33794760/34642597-97277036-f33b-11e7-996b-926ac2fde904.png)

- [ ] This tile overlapped with menu.
![image](https://user-images.githubusercontent.com/33794760/34642612-e586dd3e-f33b-11e7-8eba-7fd2cb895fd8.png)

- [ ] Make a way for use key and go to the next level.
- [ ] Add arrows and bows in several places to picks as an inventory when we enter to some places there are monsters without bows we died. we must have bows. Add things like these.
          - Add dangerous fishes. without feed them with food we can't proceed.
          - Add autocratically blasts bombs, So player has to exit from that area within given time.
          - Add invisible potion for save life from monsters.
          - Add stair cases for go to underground and new tiles layer must be there.
          - ........................................................................................................................
## Would you like to work on this
Help needs from all

**Comment by YashKumarVerma** [comment]
Suggestions are great 🔥

**Comment by niccokunzmann** [comment]
#204 will change some layout.

**Comment by STEdirisuriya** [comment]
@YashKumarVerma thank you! help for make labyrinth a good game!

**Comment by naveentherocker** [comment]
I am working on a section of this `Add an about window and add social icons, UI creator, Contributors, a brief description on it.`

**Comment by naveentherocker** [comment]
Working on this `Make same message not shows to twice.`

**Comment by Ploypiti** [comment]
Point 2 `Single color BG` is a part of #225, currently working on it.

**Comment by naveentherocker** [comment]
Working on this Use characters that haven't white space.

**Comment by STEdirisuriya** [comment]
If one point resolved please say in this.

**Comment by STEdirisuriya** [comment]
Give new ideas

**Comment by STEdirisuriya** [comment]
working on this point 

Add an about window and add social icons, UI creator, Contributors, brief description on it. (enhancement)

**Comment by abishekvashok** [comment]
Working on:
> Remove this word on tile or change word effect for looks it good. (enhancement)

**Comment by duttaditya18** [comment]
I think this is fixed.

**Comment by niccokunzmann** [comment]
@STEdirisuriya Please check.

**Comment by STEdirisuriya** [comment]
@niccokunzmann there are some steps to fix and improve yet

**Comment by STEdirisuriya** [comment]
*Add a option to change character on menu-bar. (enhancement)* step fixing from following issue.
https://github.com/fossasia/labyrinth/issues/579

* Add an about window and add social icons, UI creator, Contributors, brief description on it. (enhancement)* not yet fixed

*This tile came out from walls, please resolve it. (bug)* This is yet.

* Make same message not shows to twice. (bug)* yet

**Comment by STEdirisuriya** [comment]
As I think not single improvements yet. 
I tell about these things.

 Make a way for use key and go to the next level. (enhancement)

 Add arrows and bows in several places to picks as an inventory when we enter to some places there are monsters without bows we died. we must have bows. Add things like following. (enhancement)

 Add dangerous fishes. without feed them with food we can't proceed. (enhancement)

 Add automatically blasts bombs, So player has to exit from that area within given time. (enhancement)

 Add invisible potion for save life from monsters. (enhancement)

 Add stair cases for go to underground and new tiles layer must be there. (enhancement)
